// Date: 29/9/2024
// By: Youssef Ashraf, Nada Mohammed, Mohammed Ashraf
// Last update: 29/9/2024
// Objectives: This file is responsible for providing the translations of the application.
// Available languages now --> English, Arabic

import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // ****************************************** ENGLISH LANGUAGE ******************************************
        'en_US': {
          // add english translations here
          'Inventory Management': 'Inventory Management',
          'All': 'All',
          'Approved': 'Approved',
          'Rejected': 'Rejected',
          'Canceled': 'Canceled',
          'Pending': 'Pending',
          'Approvals': 'Approvals',
          'Department': 'Department',
          'Job Title': 'Job Title',
          'Request Information': 'Request Information',
          'Request ID': 'Request ID',
          'Consumable ID': 'Consumable ID',
          'Request Type': 'Request Type',
          'Expected Delivery': 'Expected Delivery',
          'Return Date': 'Return Date',
          'Item Information': 'Item Information',
          'Category': 'Category',
          'Subcategory': 'Subcategory',
          "Request": "Request",
          "Not Applicable": "Not Applicable",
          "Daily": "Daily",
          "Monthly": "Monthly",
          "Annually": "Annually",
          "Requests": "Requests",
          "Consumables": "Consumables",
          "Assets": "Assets",
          'Model': 'Model',
          'Brand': 'Brand',
          'Quantity': 'Quantity',
          'Additional Details': 'Additional Details',
          'Notes and Comments': 'Notes and Comments',
          'Approval': 'Approval',
          'Reject': 'Reject',
          "Track Request": "Track Request",
          'Approve': 'Approve',
          "Download": "Download",
          "Unit Of Measurement": "Unit Of Measurement",
          "Usage Frequenc": "Usage Frequency",
          "Expiration Date": "Expiration Date",
          "Status": "Status",
          "Priority": "Priority",
          "Urgent": "Urgent",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Date Return": "Date Return",
          "Maintenance Frequency": "Maintenance Frequency",
          'Expected Received': 'Expected Received',
          "Filter": "Filter",
          'Search Here...': 'Search Here...',
          'Search By Name, Category, Subcategory, Brand, Or Model':
              'Search By Name, Category, Subcategory, Brand, Or Model',
          'Request Date': 'Request Date',
          'Last Update': 'Last Update',
          'Track Asset': 'Track Asset',
          'Asset Details': 'Asset Details',
          'Write A Comment': 'Write A Comment',
          'Inquiries And Comments': 'Inquiries And Comments',

          'Employee': 'Employee',
          'Manager': 'Manager',
          'Admin': 'Admin',
          'Approval Cycle': 'Approval Cycle',
          'Requires Approvals': 'Requires Approvals',
          'Yes': 'Yes',
          'No': 'No',
          'Cancelation': 'Cancelation',
          'Cancelation Request': 'Cancelation Request',
          'Are You sure You Want to Cancel this Request ?':
              'Are You sure You Want to Cancel this Request ?',
          'Request Delivery': 'Request Delivery',

          "Asset ID": "Asset ID",
          "Asset Name": "Asset Name",
          "Next Maintenance Schedule": "Next Maintenance Schedule",
          "Date Received": "Date Received",
          "Name": "Name",
          'Consumable Request': 'Consumable Request',
          'Asset Request': 'Asset Request', "Maintenance": "Maintenance",
          "Returned": "Returned",
          "InUse": "InUse",
          "Out Stock": "Out Stock",
          "In Stock": "In Stock",
          "Availability": "Availability",
          "Additional Notes": "Additional Notes",
          "No Data Found": "No Data Found",
          "Assets ID": "Assets ID",
          "Date Receive": "Date Receive",
          'Delete': 'Delete',

          "Add New Assets": "Add New Assets",
          "Create Automatic IDs": "Create Automatic IDs",
          "Order Id": "Order Id",
          "Product Id": "Product Id",
          "Product Type": "Product Type",
          "Supplier": "Supplier",
          "Reject Approve": "Reject Approve",
          "Product ID": "Product ID",
          "My Requests": "My Requests",
          "Dashboard": "Dashboard",
          "Products": "Products",
          "Storage Location": "Storage Location",
          "Product": "Product",

          'Postal Code': 'Postal Code',
          'City': 'City',
          'Country': 'Country',
          'State Or Province': 'State Or Province',
          'Supplier Name': 'Supplier Name',
          'Supplier ID': 'Supplier ID',
          'Contract Details': 'Contract Details',
          'General Supplier Details': 'General Supplier Details',
          'General Storage Details': 'General Storage Details',
          'Order Form': 'Order Form',
          'Order ID': 'Order ID',
          'Order Value': 'Order Value',
          'Contract Start Date': 'Contract Start Date',
          'Contract End Date': 'Contract End Date',
          'Location Name': 'Location Name',
          'Location ID': 'Location ID',
          'Location Type': 'Location Type',
          'Storage Details': 'Storage Details',
          'Add New Storage': 'Add New Storage',
          'Supplier Details': 'Supplier Details',
          'Add New Supplier': 'Add New Supplier',
          'Accessibility Level': 'Accessibility Level',
          'Environment Control Type': 'Environment Control Type',
          'Orders': 'Orders',
          'Order': 'Order',
          'Suppliers': 'Suppliers',
          'Assigned': 'Assigned',
          'Quantity Assigned': 'Quantity Assigned',
          'Assigned Date': 'Assigned Date',
          'Stock': 'Stock',
          'Additional Info': 'Additional Info',
          'Storage Location And Quantity': 'Storage Location And Quantity',
          'Expected Liftetime': 'Expected Liftetime',
          'Unit Cost': 'Unit Cost',
          'Total Quantity': 'Total Quantity',
          'Currency': 'Currency',
          'Storage Requirement': 'Storage Requirement',
          'Reset': 'Reset',
          'Apply': 'Apply',
          'Product Details': 'Product Details',
          'Warranty': 'Warranty',
          'Specification': 'Specification',
          'Restocking': 'Restocking',
          'Edit': 'Edit',
          'Out Of Stock': 'Out Of Stock',
          'Asset': 'Asset',
          'Consumable': 'Consumable',
          'Track Consumable': 'Track Consumable',
          'Expected Recieved': 'Expected Recieved',
          'Overall Inventory': 'Overall Inventory',
          'Categories': 'Categories',
          'Subcategories': 'Subcategories',
          'Low Stock': 'Low Stock',
          'Warehouse': 'Warehouse',
          'Sort': 'Sort',
          'Time': 'Time',
          'Minimum': 'Minimum',
          'Maximum': 'Maximum',
          'Inventory Type': 'Inventory Type',
          'Expenses': 'Expenses',
          'Maintenance Request': 'Maintenance Request',
          "Quantity On Hand": "Quantity On Hand",
          "Supplier Id": "Supplier Id",
          "Sub Category": "Sub Category",
          "Expected Date": "Expected Date",
          "Expected Lifetime": "Expected Lifetime",
          "Description": "Description",
          "Maintenance Details": "Maintenance Details",
          "Maintenance ID": "Maintenance ID",
          "Maintenance Start Date": "Maintenance Start Date",
          "Maintenance End Date": "Maintenance End Date",
          "Next Scheduled Maintenance": "Next Scheduled Maintenance",
          "Service Provider Information": "Service Provider Information",
          "Service Provider": "Service Provider",
          "Description or Issue Reported": "Description or Issue Reported",
          "Was A Part Replaced ?": "Was A Part Replaced ?",
          "Warranty Coverage": "Warranty Coverage",
          "Maintenance Approved By": "Maintenance Approved By",
          "Warranty Expiration Date": "Warranty Expiration Date",
          "Date Of Approval": "Date Of Approval",
          "Download As PNG": "Download As PNG",
          "Service History": "Service History",
          "Retrieve": "Retrieve",
          "Email": "Email",
          "Phone Number": "Phone Number",
          "Maintenance Schedule": "Maintenance Schedule",
          "Requested Maintenance": "Requested Maintenance",
          "Returned Date": "Returned Date",
          "Issue Type": "Issue Type",
          "Request Repair Date": "Request Repair Date",
          "Repair Details": "Repair Details",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Consumables ID": "Consumables ID",
          "Consumables Name": "Consumables Name",
          "SubCategory": "SubCategory",
          "Consumables Details": "Consumables Details",
          "Reorder Level": "Reorder Level",
          "Request type": "Request type",
          "Expected Return": "Expected Return",
          "Unit Of Frequency": "Unit Of Frequency",
          "Hide": "Hide",
          "Expand": "Expand",
          'Invoices': 'Invoices',
          'Send Invoice': 'Send Invoice',
          'Order Done By ': 'Order Done By',
          'Total Price': 'Total Price',
          'NO': 'NO',
          'Product Name': 'Product Name',
          'FINAL AMOUNT': 'FINAL AMOUNT',
          'AMOUNT': 'AMOUNT',
          'ARTICLE': 'ARTICLE',
          'QUANTITY': 'QUANTITY',
          'UNIT PRICE': 'UNIT PRICE',
          'Tax Number': 'Tax Number',
          'Order Date': 'Order Date',
          'Recieving Date': 'Recieving Date',
          'Completed': 'Completed',
          'Waiting': 'Waiting',
          'Cancelled': 'Cancelled',
          'Add More Storage': 'Add More Storage',
          'Add More': 'Add More',
          'Date Has Been Save': 'Date Has Been Save',
          'Compliance Document': 'Compliance Document',
          'Business Type': 'Business Type',
          'Employee Details': 'Employee Details',
          'You Sent The Invoice': 'You Sent The Invoice',
          'Success': 'Success',
          'Error': 'Error',
          'Erro Occured, Please Try Again': 'Erro Occured, Please Try Again',
          'Document Has Been Saved': 'Document Has Been Saved',
          'Reorder Quantity': 'Reorder Quantity',
          'Usage Frequency': 'Usage Frequency',
          'Consumable Name': 'Consumable Name',

          'Storage Capacity': 'Storage Capacity',
          'Condition Of Storage': 'Condition Of Storage',
          'Environmental Control Type': 'Environmental Control Type',

          'Equipment Available': 'Equipment Available',
          'Processing': 'Processing',
          'Proposed Contact': 'Proposed Contact',
          'Compliance Contact': 'Compliance Contact',
          'Point Contact Name': 'Point Contact Name',
          'Catalog Of Product': 'Catalog Of Product',
          'Invoice': 'Invoice',
          'Assing Employee': 'Assing Employee',
          'Enter': 'Enter',
          'choice': 'choice',
          'Point Of Contract': 'Point Of Contract',
        },

        // ****************************************** ARABIC LANGUAGE ******************************************
        'ar_EG': {
          // add arabic translations here

          'Inventory Management': 'إدارة المخزون',

          'All': 'الكل',
          'Approved': 'مقبول',
          'Rejected': 'مرفوض',
          'Canceled': 'ملغى',
          'Pending': 'قيد الانتظار',
          'Approvals': 'الموافقات',
          'Department': 'القسم',
          'Job Title': 'المسمى الوظيفي',
          'Request Information': 'معلومات الطلب',
          'Request ID': 'رقم الطلب',
          'Consumable ID': 'رقم المستهلك',
          "Request": "طلب",
          "Requests": "الطلبات",
          "Not Applicable": "غير قابل للتطبيق",
          'Request Type': 'نوع الطلب',
          'Expected Delivery': 'التسليم المتوقع',
          'Return Date': 'تاريخ العودة',
          'Item Information': 'معلومات العنصر',
          'Category': 'الفئة',
          'Subcategory': 'الفئة الفرعية',
          'Model': 'الموديل',
          'Brand': 'العلامة التجارية',
          'Quantity': 'الكمية',
          'Additional Details': 'تفاصيل إضافية',
          'Notes and Comments': 'ملاحظات وتعليقات',
          'Approval': 'الموافقة',
          'Reject': 'رفض',
          'Approve': 'قبول',
          "Consumables": "المواد الاستهلاكية",
          "Assets": "السلع",
          "Track Request": "تتبع الطلب",
          "Download": "تحميل",
          "Unit Of Measurement": "وحدة القياس",
          "Usage Frequency": "تكرار الاستخدام",
          "Expiration Date": "تاريخ انتهاء الصلاحية",
          "Status": "الحالة",
          "Priority": "الأولوية",
          "Urgent": "عاجل",
          "High": "عالية",
          "Medium": "متوسطة",
          "Low": "منخفضة",
          "Maintenance Frequency": "تكرار الصيانة",
          'Expected Received': 'توقع الاستلام',
          "Daily": "يومي",
          "Monthly": "شهري",
          "Annually": "سنوي",
          "Filter": "تصفية",
          'Search Here...': 'ابحث هنا...',
          "Request Date": "تاريخ الطلب",
          "Last Update": "آخر تحديث",
          "Track Asset": "تتبع السلعة",
          "Asset Details": "تفاصيل السلعة",
          'Search By Name, Category, Subcategory, Brand, Or Model':
              'ابحث حسب الاسم أو الفئة أو الفئة الفرعية أو العلامة التجارية أو الطراز',
          'Write A Comment': 'اكتب تعليق',
          'Inquiries And Comments': 'الاستفسارات والتعليقات',
          'Employee': 'موظف',
          'Manager': 'مدير',
          'Admin': 'مسؤول',
          'Cancelation': 'الإلغاء', "Approval Cycle": "دورة الموافقة",
          "Requires Approvals": "يتطلب موافقات",
          "Yes": "نعم",
          "No": "لا", "Cancelation Request": "طلب الإلغاء",
          "Are You sure You Want to Cancel this Request ?":
              "هل أنت متأكد أنك تريد إلغاء هذا الطلب؟",
          'Request Delivery': 'تاريخ تسليم الطلب',

          'Consumable Request': 'طلب مستهلك',
          'Asset Request': 'طلب سلعة',
          'Delete': 'حذف',
          "Asset ID": "معرف الأصل",
          "Asset Name": "اسم الأصل",
          "Next Maintenance Schedule": "الجدول الزمني للصيانة القادمة",
          "Date Received": "تاريخ الاستلام",
          "Date Return": "تاريخ الإرجاع",
          "Name": "الاسم",
          "Maintenance": "الصيانة",
          "Returned": "تم الإرجاع",
          "InUse": "قيد الاستخدام",
          "Expired": "منتهي الصلاحية",
          "Out Stock": "غير متوفر",
          "In Stock": "متوفر",
          "Availability": "التوفر",
          "Additional Notes": "ملاحظات إضافية",
          "No Data Found": "لم يتم العثور على بيانات",
          "Assets ID": "معرف الأصول",
          "Date Receive": "تاريخ الاستلام",
          "Consumables Details": "تفاصيل المستهلكات",
          "Add New Assets": "إضافة أصول جديدة",
          "Create Automatic IDs": "إنشاء معرفات تلقائية",
          "Order Id": "معرف الطلب",
          "Product Id": "معرف المنتج",

          "Product Type": "نوع المنتج",
          "Supplier": "المورد",
          "Reject Approve": "رفض/موافقة",
          "Product ID": "معرف المنتج",
          "My Requests": "طلباتي",
          "Dashboard": "لوحة التحكم",
          "Products": "المنتجات",
          "Storage Location": "موقع التخزين",
          "Product": "منتج", 'Postal Code': 'الرمز البريدي',
          'City': 'المدينة',
          'Country': 'الدولة',
          'State Or Province': 'الولاية أو المقاطعة',
          'Supplier Name': 'اسم المورد',
          'Supplier ID': 'رقم تعريف المورد',
          'Contract Details': 'تفاصيل العقد',
          'General Supplier Details': 'تفاصيل المورد العامة',
          'General Storage Details': 'تفاصيل التخزين العامة',
          'Order Form': 'نموذج الطلب',
          'Order ID': 'رقم الطلب',
          'Order Value': 'قيمة الطلب',
          'Contract Start Date': 'تاريخ بدء العقد',
          'Contract End Date': 'تاريخ انتهاء العقد',
          'Location Name': 'اسم الموقع',
          'Location ID': 'رقم تعريف الموقع',
          'Location Type': 'نوع الموقع',
          'Storage Details': 'تفاصيل التخزين',
          'Add New Storage': 'إضافة تخزين جديد',
          'Supplier Details': 'تفاصيل المورد',
          'Add New Supplier': 'إضافة مورد جديد',
          'Accessibility Level': 'مستوى الوصول',
          'Environment Control Type': 'نوع التحكم في البيئة',
          'Orders': 'الطلبات',
          'Order': 'طلب', 'Suppliers': 'الموردين',

          'Assigned': 'تم التخصيص',
          'Quantity Assigned': 'الكمية المخصصة',
          'Assigned Date': 'تاريخ التخصيص',
          'Stock': 'المخزون',
          'Additional Info': 'معلومات إضافية',
          'Storage Location And Quantity': 'موقع التخزين والكمية',
          'Expected Liftetime': 'العمر الافتراضي المتوقع',
          'Unit Cost': 'تكلفة الوحدة',
          'Total Quantity': 'إجمالي الكمية',
          'Currency': 'العملة',
          'Storage Requirement': 'متطلبات التخزين',
          'Reset': 'إعادة تعيين',
          'Apply': 'تطبيق',
          'Product Details': 'تفاصيل المنتج',
          'Warranty': 'الضمان',
          'Specification': 'المواصفات',
          'Restocking': 'إعادة التخزين',
          'Edit': 'تعديل',
          'Out Of Stock': 'غير متوفر',
          'Asset': 'الأصل',
          'Consumable': 'قابل للاستهلاك',
          'Track Consumable': 'تتبع المواد الاستهلاكية',
          'Expected Recieved': 'المتوقع استلامه',
          'Overall Inventory': 'إجمالي المخزون',
          'Categories': 'الفئات',
          'Subcategories': 'الفئات الفرعية',
          'Low Stock': 'مخزون منخفض',
          'Warehouse': 'المستودع',
          'Sort': 'ترتيب',
          'Time': 'الوقت',
          'Minimum': 'الحد الأدنى',
          'Maximum': 'الحد الأقصى',
          'Inventory Type': 'نوع المخزون',
          'Expenses': 'المصروفات',
          'Maintenance Request': 'طلب صيانة',

          "Quantity On Hand": "الكمية المتوفرة",
          "Supplier Id": "معرف المورد",
          "Sub Category": "الفئة الفرعية",
          "Expected Date": "التاريخ المتوقع",
          "Expected Lifetime": "العمر المتوقع",
          "Description": "الوصف",
          "Maintenance Details": "تفاصيل الصيانة",
          "Maintenance ID": "معرف الصيانة",
          "Maintenance Start Date": "تاريخ بدء الصيانة",
          "Maintenance End Date": "تاريخ انتهاء الصيانة",
          "Next Scheduled Maintenance": "الصيانة المجدولة التالية",
          "Service Provider Information": "معلومات مزود الخدمة",
          "Service Provider": "مزود الخدمة",
          "Description or Issue Reported": "الوصف أو المشكلة المبلغ عنها",
          "Was A Part Replaced ?": "هل تم استبدال جزء؟",
          "Warranty Coverage": "تغطية الضمان",
          "Maintenance Approved By": "تمت الموافقة على الصيانة بواسطة",
          "Warranty Expiration Date": "تاريخ انتهاء الضمان",
          "Date Of Approval": "تاريخ الموافقة",
          "Download As PNG": "تنزيل كصورة PNG",
          "Service History": "سجل الخدمة",
          "Retrieve": "استرجاع",
          "Email": "البريد الإلكتروني",
          "Phone Number": "رقم الهاتف",
          "Maintenance Schedule": "جدول الصيانة",
          "Requested Maintenance": "الصيانة المطلوبة",
          "Returned Date": "تاريخ الإرجاع",
          "Issue Type": "نوع المشكلة",
          "Request Repair Date": "تاريخ طلب الإصلاح",
          "Repair Details": "تفاصيل الإصلاح",
          "First Name": "الاسم الأول",
          "Last Name": "الاسم الأخير",
          "Consumables ID": "معرف المستهلكات",
          "Consumables Name": "اسم المستهلكات",
          "SubCategory": "الفئة الفرعية",
          "Unit Measurement": "وحدة القياس",
          "Reorder Point": "نقطة إعادة الطلب",
          "Reorder Quantity": "كمية إعادة الطلب",
          "Reorder Level": "مستوى إعادة الطلب",
          "Request type": "نوع الطلب",
          "Expected Return": "العودة المتوقعة",
          "Unit Of Frequency": "وحدة التردد",
          "Hide": "إخفاء",
          "Expand": "توسيع",
          'Invoices': 'الفواتير',
          'Send Invoice': 'إرسال الفاتورة',
          'Order Done By ': 'تم الطلب بواسطة',
          'Total Price': 'السعر الإجمالي',
          'NO': 'الرقم',
          'Product Name': 'اسم المنتج',
          'FINAL AMOUNT': 'المبلغ النهائي',
          'AMOUNT': 'المبلغ',
          'ARTICLE': 'المقال',
          'QUANTITY': 'الكمية',
          'Total Picked Files': 'Total Picked Files',
          'UNIT PRICE': 'سعر الوحدة',
          'Tax Number': 'الرقم الضريبي',
          'Order Date': 'تاريخ الطلب',
          'Recieving Date': 'تاريخ الاستلام',
          'Completed': 'مكتمل',
          'Waiting': 'قيد الانتظار',
          'Cancelled': 'ملغى',
          'Add More Storage': 'إضافة المزيد من التخزين',
          'Add More': 'إضافة المزيد',
          'Date Has Been Save': 'تم حفظ البيانات',
          'Compliance Document': 'وثيقة الامتثال',
          'Business Type': 'نوع العمل',
          'Employee Details': 'تفاصيل الموظف',
          'You Sent The Invoice': 'لقد أرسلت الفاتورة',
          'Success': 'نجاح',
          'Error': 'خطأ',
          'Erro Occured, Please Try Again': 'حدث خطأ، يرجى المحاولة مرة أخرى',
          'Document Has Been Saved': 'تم حفظ المستند',

          'Consumable Name': 'اسم المواد الاستهلاكية',
          'Storage Capacity': 'سعة التخزين',
          'Condition Of Storage': 'حالة التخزين',
          'Environmental Control Type': 'نوع التحكم البيئي',
          'Equipment Available': 'المعدات المتاحة',
          'Processing': 'يتم التجهيز',
          'Proposed Contact': 'جهة الاتصال المقترحة',
          'Compliance Contact': 'جهة الاتصال الخاصة بالامتثال',
          'Point Contact Name': 'اسم جهة الاتصال الأساسية',
          'Catalog Of Product': 'كتالوج المنتجات',
          'Invoice': 'فاتورة',
          'Assing Employee': 'تعيين موظف',
          'Enter': 'ادخل',
          'choice': 'اختر',
          'Point Of Contract': 'نقطة الاتصال',
        },
      };
}
